In [1]:
import pandas as pd
from scipy.signal import find_peaks
import numpy as np
import plotly.graph_objs as go

df = pd.DataFrame({'date': ['2023-05-01', '2023-05-02', '2023-05-03', '2023-05-04', '2023-05-05', '2023-05-06', '2023-05-07','2023-05-08'],
                   'open': [100, 105, 110, 115, 120, 125, 130,130],
                   'high': [105, 110, 95, 120, 125, 100, 135,120],
                   'low': [105, 100, 105, 110, 115, 120, 125,150],
                   'close': [101, 106, 111, 116, 121, 126, 131,103]})

high_peaks = find_peaks(df['high'].values)[0]
df['high_local_max'] = df.iloc[high_peaks]['high']
low_peaks= find_peaks(-df['low'].values)[0]
df['low_local_min'] = df.iloc[low_peaks]['low']

print(df)

         date  open  high  low  close  high_local_max  low_local_min
0  2023-05-01   100   105  105    101             NaN            NaN
1  2023-05-02   105   110  100    106           110.0          100.0
2  2023-05-03   110    95  105    111             NaN            NaN
3  2023-05-04   115   120  110    116             NaN            NaN
4  2023-05-05   120   125  115    121           125.0            NaN
5  2023-05-06   125   100  120    126             NaN            NaN
6  2023-05-07   130   135  125    131           135.0            NaN
7  2023-05-08   130   120  150    103             NaN            NaN


In [2]:
find_peaks(-df['high'].values)[0]

array([2, 5])

In [3]:
from scipy.signal import argrelextrema
support_idx = argrelextrema(df['low'].values, np.less_equal, order=5)[0]
resistance_idx = argrelextrema(df['high'].values, np.greater_equal, order=5)[0]

In [4]:
support_idx

array([1])

In [5]:
resistance_idx

array([6])

In [6]:
fig = go.Figure(data=[go.Candlestick(x=df['date'],
                open=df['open'], high=df['high'],
                low=df['low'], close=df['close'])])

In [7]:
from scipy.signal import argrelextrema
support_idx = argrelextrema(df['low'].values, np.less_equal, order=5)[0]
resistance_idx = argrelextrema(df['high'].values, np.greater_equal, order=5)[0]
support_shapes = []
for i in support_idx:
    support_shapes.append(dict(type='line', x0=df['date'][i], y0=df['low'][i], x1=df['date'][i+1], y1=df['low'][i], line=dict(color='green', width=1)))
    
resistance_shapes = []
for i in resistance_idx:
    resistance_shapes.append(dict(type='line', x0=df['date'][i], y0=df['high'][i], x1=df['date'][i+1], y1=df['high'][i], line=dict(color='red', width=1)))
fig.update_layout(shapes=support_shapes + resistance_shapes)
fig.show()